package ac.at.tuwien.ifs.sepses.vocab;/* CVS $Id: $ */

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from file:/Users/juang/CodeRepo/Sepses/cyber-kb/src/main/resources/owl/CAPEC.ttl
 *
 * @author Auto-generated by schemagen on 09 Apr 2019 09:07
 */
public class TL {
    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://127.0.0.1:3333/threatlist/#";
    public static final String NS_INSTANCE = "http://127.0.0.1:3333/threatlist>";
    /**
     * <p>The RDF model that holds the vocabulary terms</p>
     */
    private static Model m_model = ModelFactory.createDefaultModel();
    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = m_model.createResource(NS);
    public static final Property ID = m_model.createProperty("http://127.0.0.1:3333/threatlist");
    public static final Property TITLE = m_model.createProperty("http://127.0.0.1:3333/threatlist");
    public static final Property CATEGORY = m_model.createProperty("http://127.0.0.1:3333/category");
    public static final Property DIAGRAM = m_model.createProperty("http://127.0.0.1:3333/diagram");
    public static final Property INTERACTION = m_model.createProperty("http://127.0.0.1:3333/interaction");
    public static final Property PRIORITY = m_model.createProperty("http://127.0.0.1:3333/priority");
    public static final Property STATE = m_model.createProperty("http://127.0.0.1:3333/STATE");
    public static final Property CHANGED_BY = m_model.createProperty("http://127.0.0.1:3333/changedby");
    public static final Property DESCRIPTION = m_model.createProperty("http://127.0.0.1:3333/description");
    public static final Property JUSTIFICATION = m_model.createProperty("http://127.0.0.1:3333/justification");
    public static final Property LAST_MODIFIED = m_model.createProperty("http://127.0.0.1:3333/lastmodified");
    public static final Property POSSIBLE_MITIGATIONS = m_model.createProperty("http://127.0.0.1:3333/possiblemittigations");
    public static final Property SDL_PHASE = m_model.createProperty("http://127.0.0.1:3333/sdlphase");
    public static final Resource RELATED_WEAKNESS = m_model.createResource("http://w3id.org/sepses/vocab/ref/capec#RelatedWeakness");

    public static final Resource TL = m_model.createResource("http://127.0.0.1:3333/threatlist");
    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

}